/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.mycompany.javaproject1;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.FlowLayout;
import java.awt.GridLayout;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTabbedPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;

import java.awt.BorderLayout;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author Hansaka
 */
public class Farmerinventory extends javax.swing.JInternalFrame {
    
    // Database Config
    private final String DB_URL = "jdbc:mysql://localhost:3306/ecofarm";
    private final String DB_USER = "root";
    private final String DB_PASSWORD = ""; 

    // UI Components for the Management Tab
    private JComboBox<String> categorySelector;
    private JTable dataTable;
    private DefaultTableModel tableModel;
    private JTextField txtField1, txtField2, txtField3; // Generic fields for inputs
    private JLabel lblField1, lblField2, lblField3;     // Generic labels that change text
    
    
     /**
     * Creates new form crop
     */
    public Farmerinventory() {
        initComponents();
        
        // 1. Basic Setup
        this.setBorder(BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI)this.getUI();
        ui.setNorthPane(null);
        this.getContentPane().setLayout(new BorderLayout());

        // 2. Create Tabbed Pane
        JTabbedPane tabbedPane = new JTabbedPane();
        
        // --- TAB 1: DASHBOARD (Your Charts) ---
        JPanel dashboardPanel = new JPanel(new BorderLayout());
        dashboardPanel.add(new diagram(), BorderLayout.CENTER);
        tabbedPane.addTab("Dashboard Charts", dashboardPanel);

        // --- TAB 2: DATA MANAGER (Edit/Update/Delete) ---
        // We call the method that builds the management UI
        JPanel managerPanel = createManagementPanel(); 
        tabbedPane.addTab("Edit Data", managerPanel);

        this.getContentPane().add(tabbedPane, BorderLayout.CENTER);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 848, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 574, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // --- 1. BUILD THE MANAGEMENT UI ---
    private JPanel createManagementPanel() {
        JPanel panel = new JPanel(new BorderLayout());
        
        // Top: Dropdown to select table
        JPanel topPanel = new JPanel(new FlowLayout(FlowLayout.LEFT));
        topPanel.add(new JLabel("Select Table: "));
        String[] categories = {"Organics", "Fertilizers", "Seeds", "Equipment"};
        categorySelector = new JComboBox<>(categories);
        categorySelector.addActionListener(e -> loadDataForCategory()); // Reload when changed
        topPanel.add(categorySelector);
        panel.add(topPanel, BorderLayout.NORTH);

        // Center: Data Table
        tableModel = new DefaultTableModel();
        dataTable = new JTable(tableModel);
        // Click listener to fill text boxes
        dataTable.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent e) {
                fillFormFromTable();
            }
        });
        panel.add(new JScrollPane(dataTable), BorderLayout.CENTER);

        // Bottom: Input Fields & Buttons
        JPanel bottomContainer = new JPanel(new BorderLayout());
        
        // Inputs Grid
        JPanel inputPanel = new JPanel(new GridLayout(3, 2, 5, 5));
        inputPanel.setBorder(BorderFactory.createTitledBorder("Edit Details"));
        
        lblField1 = new JLabel("Field 1"); txtField1 = new JTextField();
        lblField2 = new JLabel("Field 2"); txtField2 = new JTextField();
        lblField3 = new JLabel("Field 3"); txtField3 = new JTextField();

        inputPanel.add(lblField1); inputPanel.add(txtField1);
        inputPanel.add(lblField2); inputPanel.add(txtField2);
        inputPanel.add(lblField3); inputPanel.add(txtField3);
        bottomContainer.add(inputPanel, BorderLayout.CENTER);

        // Buttons
        JPanel btnPanel = new JPanel(new FlowLayout());
        JButton btnAdd = new JButton("ADD");
        JButton btnUpdate = new JButton("UPDATE");
        JButton btnDelete = new JButton("DELETE");
        JButton btnClear = new JButton("CLEAR");

        // Button Actions
        btnAdd.addActionListener(e -> executeSQL("INSERT"));
        btnUpdate.addActionListener(e -> executeSQL("UPDATE"));
        btnDelete.addActionListener(e -> executeSQL("DELETE"));
        btnClear.addActionListener(e -> { txtField1.setText(""); txtField2.setText(""); txtField3.setText(""); });

        btnPanel.add(btnAdd); btnPanel.add(btnUpdate); btnPanel.add(btnDelete); btnPanel.add(btnClear);
        bottomContainer.add(btnPanel, BorderLayout.SOUTH);
        
        panel.add(bottomContainer, BorderLayout.SOUTH);

        loadDataForCategory(); // Load initial data
        return panel;
    }

    // --- 2. DYNAMIC DATA LOADING ---
    private void loadDataForCategory() {
        String category = (String) categorySelector.getSelectedItem();
        tableModel.setRowCount(0); // Clear table
        
        // Configure Labels/Visibility based on selection
        if (category.equals("Organics")) {
            lblField1.setText("Month (ID):");
            lblField2.setText("Amount (KG):");
            lblField3.setVisible(false); txtField3.setVisible(false);
            tableModel.setColumnIdentifiers(new Object[]{"Month", "KG"});
        } else if (category.equals("Fertilizers")) {
            lblField1.setText("Month (ID):");
            lblField2.setText("Amount:");
            lblField3.setVisible(false); txtField3.setVisible(false);
            tableModel.setColumnIdentifiers(new Object[]{"Month", "Amount"});
        } else if (category.equals("Seeds")) {
            lblField1.setText("ID:");
            lblField2.setText("Name:");
            lblField3.setText("Percentage:");
            lblField3.setVisible(true); txtField3.setVisible(true);
            tableModel.setColumnIdentifiers(new Object[]{"ID", "Name", "Percentage"});
        } else { // Equipment
            lblField1.setText("ID:");
            lblField2.setText("Farmer Name:");
            lblField3.setText("Equipment:");
            lblField3.setVisible(true); txtField3.setVisible(true);
            tableModel.setColumnIdentifiers(new Object[]{"ID", "Farmer Name", "Equipment"});
        }

        try {
            Connection con = DriverManager.getConnection(DB_URL, DB_USER, DB_PASSWORD);
            Statement stmt = con.createStatement();
            ResultSet rs;
            
            // Run Query
            if(category.equals("Organics")) rs = stmt.executeQuery("SELECT monthly, kg FROM organics");
            else if(category.equals("Fertilizers")) rs = stmt.executeQuery("SELECT monthly, amount FROM fertilizers");
            else if(category.equals("Seeds")) rs = stmt.executeQuery("SELECT ID, name, percentage FROM seed");
            else rs = stmt.executeQuery("SELECT ID, farmer_name, equipment FROM equipment");

            while(rs.next()) {
                if(category.equals("Equipment")) 
                    tableModel.addRow(new Object[]{rs.getString(1), rs.getString(2), rs.getString(3)});
                else if(category.equals("Seeds"))
                    tableModel.addRow(new Object[]{rs.getString(1), rs.getString(2), rs.getString(3)});
                else
                    tableModel.addRow(new Object[]{rs.getString(1), rs.getString(2)});
            }
            con.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    // --- 3. FILL TEXT BOXES ON CLICK ---
    private void fillFormFromTable() {
        int row = dataTable.getSelectedRow();
        if (row != -1) {
            txtField1.setText(tableModel.getValueAt(row, 0).toString());
            txtField2.setText(tableModel.getValueAt(row, 1).toString());
            if (tableModel.getColumnCount() > 2) 
                txtField3.setText(tableModel.getValueAt(row, 2).toString());
        }
    }

    // --- 4. EXECUTE INSERT/UPDATE/DELETE ---
    private void executeSQL(String action) {
        String category = (String) categorySelector.getSelectedItem();
        String f1 = txtField1.getText();
        String f2 = txtField2.getText();
        String f3 = txtField3.getText();

        try {
            Connection con = DriverManager.getConnection(DB_URL, DB_USER, DB_PASSWORD);
            PreparedStatement pst = null;
            String sql = "";

            // LOGIC FOR ORGANICS & FERTILIZERS (2 Columns)
            if (category.equals("Organics") || category.equals("Fertilizers")) {
                String table = category.toLowerCase(); // 'organics' or 'fertilizers'
                String col2 = category.equals("Organics") ? "kg" : "amount";
                
                if (action.equals("INSERT")) {
                    sql = "INSERT INTO " + table + " (monthly, " + col2 + ") VALUES (?, ?)";
                    pst = con.prepareStatement(sql); pst.setString(1, f1); pst.setString(2, f2);
                } else if (action.equals("UPDATE")) {
                    sql = "UPDATE " + table + " SET " + col2 + "=? WHERE monthly=?";
                    pst = con.prepareStatement(sql); pst.setString(1, f2); pst.setString(2, f1);
                } else if (action.equals("DELETE")) {
                    sql = "DELETE FROM " + table + " WHERE monthly=?";
                    pst = con.prepareStatement(sql); pst.setString(1, f1);
                }
            } 
            // LOGIC FOR SEEDS & EQUIPMENT (3 Columns)
            else { 
                if (action.equals("INSERT")) {
                    if(category.equals("Seeds")) {
                       sql = "INSERT INTO seed (name, percentage) VALUES (?, ?)";
                       pst = con.prepareStatement(sql); pst.setString(1, f2); pst.setString(2, f3);
                    } else {
                       sql = "INSERT INTO equipment (farmer_name, equipment, email) VALUES (?, ?, 'N/A')";
                       pst = con.prepareStatement(sql); pst.setString(1, f2); pst.setString(2, f3);
                    }
                } else if (action.equals("UPDATE")) {
                    if(category.equals("Seeds")) sql = "UPDATE seed SET name=?, percentage=? WHERE ID=?";
                    else sql = "UPDATE equipment SET farmer_name=?, equipment=? WHERE ID=?";
                    pst = con.prepareStatement(sql); pst.setString(1, f2); pst.setString(2, f3); pst.setString(3, f1);
                } else if (action.equals("DELETE")) {
                    String table = category.equals("Seeds") ? "seed" : "equipment";
                    sql = "DELETE FROM " + table + " WHERE ID=?";
                    pst = con.prepareStatement(sql); pst.setString(1, f1);
                }
            }

            if(pst != null) {
                pst.executeUpdate();
                JOptionPane.showMessageDialog(this, "Success!");
                loadDataForCategory(); // Refresh Table
                con.close();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
