/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.mycompany.javaproject1;

import java.awt.BorderLayout;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author Hansaka
 */
public class Inventory extends javax.swing.JInternalFrame {
    
    
     /**
     * Creates new form crop
     */
    public Inventory() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI)this.getUI();
        ui.setNorthPane(null);
        
        
        // --- ADDED CODE STARTS HERE ---
        
        // 1. Set the layout of the Inventory frame to BorderLayout
        // This ensures the charts fill the entire available space
        this.getContentPane().setLayout(new BorderLayout());
        
        // 2. Create an object of your diagram class
        diagram myDashboard = new diagram();
        
        // 3. Add the dashboard to the Center of this frame
        this.getContentPane().add(myDashboard, BorderLayout.CENTER);
        
        // --- ADDED CODE ENDS HERE ---
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 848, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 574, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
