/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.mycompany.javaproject1;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.JTable; // Important for the error fix
import javax.swing.table.DefaultTableModel;

import java.awt.Color;
import java.awt.Component;
import java.awt.Font;
import javax.swing.JTable;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableCellRenderer;

/**
 *
 * @author Hansaka
 */
public class Markertplace extends javax.swing.JInternalFrame {
    
    
    // 1. Database Variables
    private final String DB_URL = "jdbc:mysql://localhost:3306/ecofarm";
    private final String DB_USER = "root";
    private final String DB_PASSWORD = ""; 

    // 2. Method to Load Data from 'orders' table
    private void loadOrdersData() {
        try {
            Connection con = DriverManager.getConnection(DB_URL, DB_USER, DB_PASSWORD);
            Statement stmt = con.createStatement();
            String sql = "SELECT * FROM orders";
            ResultSet rs = stmt.executeQuery(sql);
            
            // Your table variable is named 'jTablel' (lowercase L)
            DefaultTableModel model = (DefaultTableModel) jTablel.getModel();
            model.setRowCount(0); // Clear existing data
            
            while(rs.next()) {
                Vector v = new Vector();
                v.add(rs.getInt("order_id"));
                v.add(rs.getInt("product_id"));
                v.add(rs.getInt("amount"));
                model.addRow(v);
            }
            con.close();
            
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error loading orders: " + e.getMessage());
        }
    }
    
    
    
     /**
     * Creates new form crop
     */
 public Markertplace() {
        // 1. THIS MUST BE FIRST
        initComponents(); 
        
        // 2. Load Database Data
        loadOrdersData();
        
        // 3. Table Styling (AFTER components are created)
        // Note: Using 'jTablel' (lowercase L) as per your generated code
        jTablel.getTableHeader().setDefaultRenderer(new HeaderColor());
        jTablel.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 12));
        jTablel.getTableHeader().setOpaque(false);
        jTablel.getTableHeader().setBackground(new Color(32, 136, 203));
        jTablel.getTableHeader().setForeground(new Color(255, 255, 255));
        jTablel.setRowHeight(25);
        
        // 4. Remove Borders
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI)this.getUI();
        ui.setNorthPane(null);
    }
    
      public class HeaderColor extends DefaultTableCellRenderer {

        public HeaderColor() {
            setOpaque(true);
        }

      // CHANGE: First word must be 'JTable' (Capital J), NOT 'jTablel'
        @Override
        public Component getTableCellRendererComponent(JTable table, Object value, boolean selected, boolean focused, int row, int column) {
            super.getTableCellRendererComponent(table, value, selected, focused, row, column);
            
            setBackground(new java.awt.Color(32, 136, 203));
            return this;
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTablel = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTablel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Order ID", "Product ID", "Amount"
            }
        ));
        jTablel.setFocusable(false);
        jTablel.setRowHeight(25);
        jTablel.setSelectionBackground(new java.awt.Color(232, 57, 95));
        jTablel.setShowHorizontalLines(true);
        jTablel.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTablel);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 94, 840, 343));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bg.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablel;
    // End of variables declaration//GEN-END:variables
}
